-- webhook_events table
CREATE TABLE IF NOT EXISTS public.webhook_events (
  id BIGINT GENERATED BY DEFAULT AS IDENTITY NOT NULL,
  user_id UUID NULL,
  project_id UUID NULL,
  method TEXT NOT NULL,
  url TEXT NOT NULL,
  headers JSONB NULL,
  body JSONB NULL,
  provider TEXT NULL,
  content_type TEXT NULL,
  raw_body TEXT NULL,
  query JSONB NULL,
  created_at TIMESTAMP WITH TIME ZONE NULL DEFAULT now(),
  CONSTRAINT webhook_events_pkey PRIMARY KEY (id),
  CONSTRAINT webhook_events_user_id_fkey FOREIGN KEY (user_id) REFERENCES auth.users(id) ON DELETE CASCADE,
  CONSTRAINT webhook_events_project_id_fkey FOREIGN KEY (project_id) REFERENCES projects(id) ON DELETE SET NULL
);

CREATE INDEX idx_webhook_events_user_id ON public.webhook_events USING btree (user_id);
CREATE INDEX idx_webhook_events_project_id ON public.webhook_events USING btree (project_id);
CREATE INDEX idx_webhook_events_method ON public.webhook_events USING btree (method);
CREATE INDEX idx_webhook_events_provider ON public.webhook_events USING btree (provider);
CREATE INDEX idx_webhook_events_created_at ON public.webhook_events USING btree (created_at DESC);
CREATE INDEX idx_webhook_events_content_type ON public.webhook_events USING btree (content_type);

ALTER TABLE public.webhook_events ENABLE ROW LEVEL SECURITY;

CREATE POLICY "anyone_insert_webhook_events" ON public.webhook_events FOR INSERT WITH CHECK (true);
CREATE POLICY "users_view_own_webhook_events" ON public.webhook_events FOR SELECT USING (auth.uid() = user_id);