const { createClient } = require('@supabase/supabase-js')

const supabaseUrl = 'https://ujglpeaujqwprjnrmvbp.supabase.co'
const serviceKey = 'eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6InVqZ2xwZWF1anF3cHJqbnJtdmJwIiwicm9sZSI6InNlcnZpY2Vfcm9sZSIsImlhdCI6MTc3NzA5MTk5NSwiZXhwIjoyMDkyNjY3OTk1fQ.ljNEL2MqY2GtfyoZfwExiqtg28SZBPEt4WGgcC8jisU'

const supabase = createClient(supabaseUrl, serviceKey)

async function createTable() {
  const { error } = await supabase.rpc('exec_sql', {
    query: `CREATE TABLE IF NOT EXISTS request_logs (
      id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
      method TEXT NOT NULL,
      url TEXT NOT NULL,
      headers JSONB,
      body JSONB,
      provider TEXT,
      project_name TEXT,
      content_type TEXT,
      raw_body TEXT,
      query JSONB,
      created_at TIMESTAMPTZ DEFAULT NOW()
    )`
  })
  
  console.log('Error:', error?.message || 'none')
}

createTable()