CREATE TABLE IF NOT EXISTS request_logs (
  id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  user_id UUID REFERENCES auth.users(id) ON DELETE CASCADE,
  method TEXT NOT NULL,
  url TEXT NOT NULL,
  headers JSONB,
  body JSONB,
  provider TEXT,
  project_name TEXT,
  content_type TEXT,
  raw_body TEXT,
  query JSONB,
  created_at TIMESTAMPTZ DEFAULT NOW()
);

CREATE INDEX IF NOT EXISTS idx_request_logs_user_id ON public.request_logs USING btree (user_id);
CREATE INDEX IF NOT EXISTS idx_request_logs_method ON public.request_logs USING btree (method);
CREATE INDEX IF NOT EXISTS idx_request_logs_created_at ON public.request_logs USING btree (created_at);